---
cluster-autoscaler-chart:
  cloudProvider: aws
  awsRegion: eu-central-1
  autoDiscovery:
    clusterName: joe-k8s-sandbox
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
  extraArgs:
    scale-down-enabled: true
    scale-down-delay-after-add: 10m
    scale-down-delay-after-delete: 0s
    scale-down-delay-after-failure: 3m
    scale-down-unneeded-time: 10m
