kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            - name: FELIX_IPINIPENABLED
              value: "true"
            - name: CALICO_IPV4POOL_IPIP
              value: "CrossSubnet"




