apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.15.2
    helm:
      releaseName: crossplane
      values: |
        resourcesCrossplane:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
        
        resourcesRBACManager:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-crossplane
# ---
# apiVersion: pkg.crossplane.io/v1alpha1
# kind: ControllerConfig
# metadata:
#   name: jet-azure-config
#   labels:
#     app: crossplane-provider-jet-azure
# spec:
#   image: crossplane/provider-jet-azure-controller:v0.12.0-preview
#   args: ["-d"]
# ---
# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   name: crossplane-provider-jet-azure
# spec:
#   package: crossplane/provider-jet-azure:v0.12.0-preview
#   controllerConfigRef:
#     name: jet-azure-config
