apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.20.0
    helm:
      releaseName: external-dns
      # language=yaml
      values: |
        serviceAccount:
          create: false
          name: external-dns
        podAnnotations:
          azure.workload.identity/inject-proxy-sidecar: "true"
        serviceMonitor:
          enabled: true
        provider: azure
        
        extraVolumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes/
        extraVolumes:
        - name: azure-config-file
          configMap:
            name: azure-config-file
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.azure.com/mode
                      operator: In
                      values:
                        - system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-external-dns
