apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: github-exporter
    repoURL: https://jkroepke.github.io/helm-charts/
    targetRevision: 1.4.0
    helm:
      releaseName: github-exporter
      parameters:
        - name: env.GITHUB_EXPORTER_REPOSITORY
          value: jkroepke/github_exporter,jkroepke/helm-secrets,jkroepke/2Moons,jkroepke/draw-io-cncf-shape,jkroepke/homebrew-openlens,jkroepke/helm-kubectl,jkroepke/terraform-provider-azureakscommand
        - name: metrics.serviceMonitor.enabled
          value: "true"
      fileParameters:
        - name: secrets.GITHUB_EXPORTER_AUTH
          path: secrets+literal://ref+azurekeyvault://aks-credentials/github-pat

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-prometheus
