apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-event-logger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: k8s-event-logger
    repoURL: https://charts.deliveryhero.io/
    targetRevision: 1.1.8
    helm:
      releaseName: k8s-event-logger
      # language=yaml
      values: |
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.azure.com/mode
                      operator: In
                      values:
                        - system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-k8s-event-logger
