apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.5.0
    helm:
      releaseName: trivy-operator
      parameters:
        - name: trivy.ignoreUnfixed
          value: "true"
        - name: operator.scanJobsConcurrentLimit
          value: "1"
      values: |
        operator:
          scanJobTimeout: 10m
        trivy:
          ignoreUnfixed: true
          timeout: "10m0s"
          resources:
            requests:
              memory: 500Mi
              cpu: ~
            limits:
              memory: 1Gi
              cpu: ~
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=false
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-trivy-system
