controller:
  replicaCount: 3
  config:
    enable-real-ip: "true"
    real-ip-header: "proxy_protocol"
    set-real-ip-from: "10.0.0.0/8"
    use-proxy-protocol: "true"
    # For Keycloak
    # https://andrewlock.net/fixing-nginx-upstream-sent-too-big-header-error-when-running-an-ingress-controller-in-kubernetes/
    proxy-buffer-size: "16k"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: NodePort
    nodePorts:
      http: "32080"
      https: "32443"
  metrics:
    enabled: true
defaultBackend:
  enabled: true
