loki:
  config:
  # Needed for Alerting: https://grafana.com/docs/loki/latest/alerting/
  # This is just a simple example, for more details: https://grafana.com/docs/loki/latest/configuration/#ruler_config
    ruler:
      storage:
        type: local
        local:
          directory: /rules
      rule_path: /tmp/scratch
      alertmanager_url: http://monitoring-kube-prometheus-alertmanager:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true

  persistence:
    enabled: true

  alerting_groups:
    - name: example
      rules:
      - alert: HighThroughputLogStreams
        expr: sum by(container) (rate({job=~"loki-dev/.*"}[1m])) > 1000
        for: 2m

promtail:
  # Add additional scrape config
  extraScrapeConfigs:
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ['__journal__hostname']
          target_label: 'hostname'
        - source_labels: ['__journal_syslog_identifier']
          target_label: 'syslog_identifier'

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
