---
helmDefaults:
  wait: true
  timeout: 600
  atomic: true
  cleanupOnFail: true
  skipDeps: false

repositories:
  - name: flexkube
    url: https://flexkube.github.io/charts
  - name: aws-efs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: deliveryhero
    url: https://charts.deliveryhero.io/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: uswitch
    url: https://uswitch.github.io/kiam-helm-charts/charts/
  - name: codecentric
    url: https://codecentric.github.io/helm-charts
  - name: keycloak-config-cli
    url: git+https://github.com/adorsys/keycloak-config-cli@contrib/charts?ref=v2.6.2&sparse=0
  - name: gabibbo97
    url: https://gabibbo97.github.io/charts/
  - name: loki
    url: https://grafana.github.io/loki/charts

releases:
  - name: permissions
    namespace: kube-system
    chart: ./permissions

  - name: kiam
    namespace: kube-system
    needs: [ 'monitoring/monitoring' ]
    disableValidation: true
    chart: uswitch/kiam
    version: 5.9.0
    values:
      - values/kiam.yaml

  - name: cloud-provider-aws
    namespace: kube-system
    chart: ./cloud-provider-aws

  - name: calico
    namespace: kube-system
    chart: flexkube/calico
    version: 0.3.0
    values:
      - values/calico.yaml

  - name: aws-ebs-csi-driver
    namespace: kube-system
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: ./aws-ebs-csi-driver
    skipDeps: true

  - name: aws-efs-csi-driver
    namespace: kube-system
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: aws-efs-csi-driver/aws-efs-csi-driver
    version: "0.1.0"
    values:
      - values/aws-efs-csi-driver.yaml

  - name: aws-node-termination-handler
    namespace: kube-system
    chart: eks/aws-node-termination-handler
    version: "0.12.0"
    values:
      - values/aws-node-termination-handler.yaml

  - name: cluster-autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler-chart
    version: "1.1.1"
    values:
      - values/cluster-autoscaler.yaml
      - image:
          tag: v1.19.1

  - name: node-problem-detector
    namespace: kube-system
    chart: deliveryhero/node-problem-detector
    version: "1.8.0"
    values:
      - values/node-problem-detector.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: ingress-nginx/ingress-nginx
    version: "3.11.0"
    values:
      - values/ingress-nginx.yaml

  - name: cert-manager
    namespace: cert-manager
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: jetstack/cert-manager
    version: "v1.0.1"
    values:
      - values/cert-manager.yaml

  - name: cert-manager-cluster-issuer
    needs: ['cert-manager/cert-manager']
    namespace: cert-manager
    chart: ./cert-manager-cluster-issuer
    disableValidation: true

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: "2.8.2"
    values:
      - values/kubernetes-dashboard.yaml

  - name: k8s-event-logger
    namespace: k8s-event-logger
    chart: deliveryhero/k8s-event-logger
    version: "1.0"
    values:
      - values/k8s-event-logger.yaml

  - name: monitoring
    namespace: monitoring
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: prometheus/kube-prometheus-stack
    version: "12.2.0"
    values:
      - values/kube-prometheus-stack.yaml
    disableValidation: true

  - name: loki
    namespace: monitoring
    needs: [ 'monitoring/monitoring' ]
    chart: loki/loki-stack
    version: "2.1.0"
    values:
      - values/loki-stack.yaml
    disableValidation: true

  - name: keycloak
    needs: [ 'monitoring/monitoring' ]
    namespace: keycloak
    chart: codecentric/keycloak
    disableValidation: true
    version: "9.6.1"
    values:
      - values/keycloak.yaml
      - ../.local/keycloak.yaml
    strategicMergePatches:
      # https://github.com/codecentric/helm-charts/pull/352
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: keycloak
        spec:
          rules:
            - host: "login.joe-k8s-sandbox.adorsys-sandbox.aws.adorsys.de"
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: keycloak-http
                        port:
                          name: http

  - name: keycloak-config-cli
    needs: [ 'keycloak/keycloak' ]
    namespace: keycloak
    chart: keycloak-config-cli/keycloak-config-cli
    version: "2.6.2"
    values:
      - values/keycloak-config-cli.yaml
      - ../.local/keycloak-config-cli.yaml

  - name: gangway
    namespace: keycloak
    needs: [ 'kube-system/cluster-autoscaler' ]
    chart: gabibbo97/gangway
    version: "1.0.2"
    values:
      - values/gangway.yaml
