- name: set kubernetes configs
  set_fact:
    kubernetes_configs:
      - { file: kubelet, certificate: kubelet, name: "default-auth" }
      - { file: controller-manager, certificate: kube-controller-manager, name: "default-controller-manager" }
      - { file: scheduler, certificate: kube-scheduler, name: "default-scheduler" }
      - { file: cni, certificate: cni, name: "calico-cni" }

- name: kubectl config set-cluster
  command: >-
    kubectl config set-cluster default-cluster
    --server=https://{{ kubernetes.api }}:6443
    --certificate-authority /etc/kubernetes/pki/ca.crt
    --embed-certs
  environment:
    KUBECONFIG: /etc/kubernetes/{{ item.file }}.config
  loop: "{{ kubernetes_configs }}"

- name: kubectl config set-credentials
  command: >-
    kubectl config set-credentials {{ item.name }}
    --client-key /etc/kubernetes/pki/{{ item.certificate }}.key
    --client-certificate /etc/kubernetes/pki/{{ item.certificate }}.crt
    --embed-certs
  environment:
    KUBECONFIG: /etc/kubernetes/{{ item.file }}.config
  loop: "{{ kubernetes_configs }}"

- name: kubectl config set-context
  command: >-
    kubectl config set-context default-system
    --cluster default-cluster
    --user {{ item.name }}
  environment:
    KUBECONFIG: /etc/kubernetes/{{ item.name }}.config
  loop: "{{ kubernetes_configs }}"

- name: kubectl config use-context default-system
  command: >-
    kubectl config use-context default-system
  environment:
    KUBECONFIG: /etc/kubernetes/{{ item.name }}.config
  loop: "{{ kubernetes_configs }}"
