- name: set kubernetes configs
  set_fact:
    kubernetes_configs:
      - admin
      - kubelet
      - kube-controller-manager
      - kube-scheduler

- name:  kubectl config set-cluster
  command: >-
    kubectl config set-cluster kubernetes
    --certificate-authority=/etc/kubernetes/pki/ca.pem
    --embed-certs=true
    --server=https://{{ kubernetes.api }}:6443
    --kubeconfig={{ item }}.kubeconfig
  loop: "{{ kubernetes_configs }}"

- name: kubectl config set-credentials
  command: >-
    kubectl config set-credentials {{ 'system:' if 'kube' in item else '' }}{{ item }}
    --client-certificate=/etc/kubernetes/pki/{{ 'apiserver-kubelet-client' if item == 'kubelet' else item }}.crt
    --client-key=/etc/kubernetes/pki/{{ 'apiserver-kubelet-client' if item == 'kubelet' else item }}.key
    --embed-certs=true
    --kubeconfig={{ item }}.kubeconfig
  loop: "{{ kubernetes_configs }}"

- name: kubectl config set-context
  command: >-
    kubectl config set-context default
    --cluster=kubernetes
    --user={{ 'system:' if 'kube' in item else '' }}{{ item }}
    --kubeconfig={{ item }}.kubeconfig
  loop: "{{ kubernetes_configs }}"

- name: kubectl config use-context
  command: >-
    kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  loop: "{{ kubernetes_configs }}"
