# See: https://kubernetes.io/docs/setup/best-practices/certificates/

- name: set kubernetes certificates
  set_fact:
    kubernetes_certificates:
      - { name: kube-apiserver, extended_key_usage: ["serverAuth"] }
      - { name: kube-apiserver-kubelet-client, extended_key_usage: ["clientAuth"], subject: {O: "system:masters"}}
      - { name: kube-controller-manager, extended_key_usage: ["clientAuth"], common_name: "system:kube-controller-manager" }
      - { name: kube-scheduler, extended_key_usage: ["clientAuth"], common_name: "system:kube-scheduler" }
      - { name: kubelet, extended_key_usage: ["clientAuth"], common_name: "system:node:{{ ansible_fqdn }}",subject: {O: "system:nodes"}}
      - { name: cni, extended_key_usage: ["clientAuth"], common_name: "calico-cni"}}
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:{{ ansible_hostname }}"
      - "DNS:localhost"
      - "IP:{{ ansible_default_ipv6.address }}"
      - "IP:{{ ansible_default_ipv4.address }}"
      - "IP:{{ kubernetes.pod_cidr_block | regex_replace('[0-9]/[0-9][0-9]?', '1') }}"
      - "IP:127.0.0.1"
      - "IP:::1"
      - "DNS:kubernetes"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster"
      - "DNS:kubernetes.default.svc.cluster.local"

- name: create key for kubernetes certificates
  openssl_privatekey:
    path: /etc/kubernetes/pki/{{ item.name }}.key
    size: 2048
    type: RSA
  loop: "{{ kubernetes_certificates }}"

- name: create csr for kubernetes certificates
  openssl_csr:
    path: /etc/kubernetes/pki/{{ item.name }}.csr
    privatekey_path: /etc/kubernetes/pki/{{ item.name }}.key
    common_name: "{{ item.common_name | default(omit) }}"
    subject: "{{ item.subject | default(omit) }}"
    subject_alt_name: "{{ subject_alt_name if 'serverAuth' in item.extended_key_usage else omit }}"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage: "{{ item.extended_key_usage }}"
  loop: "{{ kubernetes_certificates }}"

- name: sign kubernetes certificates
  openssl_certificate:
    path: /etc/kubernetes/pki/{{ item.name }}.crt
    csr_path: /etc/kubernetes/pki/{{ item.name }}.csr
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    ownca_not_after: "+3650d"
    provider: ownca
  loop: "{{ kubernetes_certificates }}"
  notify:
    - systemctl restart kubelet
