apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    k8s-app: kube-apiserver
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
    - name: etcd
      image: quay.io/coreos/etcd:${etcd_version}
      imagePullPolicy: IfNotPresent
      command:
        - --name=${etcd_peer_name}
        - --listen-client-urls=https://${etcd_peer_name}:2379,https://127.0.0.1:2379
        - --advertise-client-urls=https://${etcd_peer_name}:2379
        - --listen-peer-urls=https://${etcd_peer_name}:2380
        - --initial-advertise-peer-urls=https://${etcd_peer_name}:2380
        - --data-dir=/var/lib/etcd/
        - --cert-file=/etc/kubernetes/pki/etcd/server.crt
        - --key-file=/etc/kubernetes/pki/etcd/server.key
        - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
        - --client-cert-auth=true
        - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
        - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
        - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
        - --peer-client-cert-auth=true
        - --snapshot-count=10000
        - --listen-metrics-urls=http://127.0.0.1:2381
        - --initial-cluster-token=etcd-cluster \
        - --initial-cluster=${initial-cluster} \
        - --initial-cluster-state=new


      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      livenessProbe:
        httpGet:
          port: 2381
          path: /health
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 15
        failureThreshold: 8
        periodSeconds: 10
      readinessProbe:
        httpGet:
          port: 2381
          path: /health
          scheme: HTTP
        initialDelaySeconds: 0
        timeoutSeconds: 15
        failureThreshold: 3
        periodSeconds: 1
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: etcd-certs
          mountPath: /var/lib/etcd/
          readOnly: true
        - name: etcd-data
          mountPath: /var/lib/etcd/
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  securityContext:
    runAsNonRoot: true
    runAsUser: 900
    runAsGroup: 900
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: etcd-certs
      hostPath:
        path: /etc/kubernetes/pki/etcd/
    - name: etcd-data
      hostPath:
        path: /var/lib/etcd/
