- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: systemctl restart kube-apiserver
  service:
    name: kube-apiserver
    state: restarted

- name: systemctl restart kube-scheduler
  service:
    name: kube-scheduler
    state: restarted

- name: systemctl restart kube-controller-manager
  service:
    name: kube-controller-manager
    state: restarted
