pki_dir: '{{ playbook_dir ~ "/../../.local/pki" }}'
kubeconfig_dir: '{{ playbook_dir ~ "/../../.local/kubeconfig" }}'
cluster_config_dir: '{{ playbook_dir ~ "/../../.local/cluster-config" }}'

kubernetes_service_cidr: 10.32.0.0/24
kubernetes_cluster_cidr: 10.200.0.0/16
kubernetes_public_hostname: api.k8s-hard-way.jkroepke.de

# https://github.com/etcd-io/etcd/releases
etcd_version: v3.4.13

# https://github.com/kubernetes/kubernetes/tags
kubernetes_version: v1.19.3
