nameOverride: "'"

test: |-
  '
  value: 0 #

nested:
  nested: '!!int 1'
  var: >-
    {{ tpl $.Values.test $ }}

args:
  - --one
  - --two
  - --three
  - '{{ $.Release.Namespace }}'

keyVar:
  "{{ $.Release.Name }}": '{{ $.Release.Namespace }}'
  "multiline": >-
    {{ template "to-yaml.labels" $ }}
