nameOverride: "'"

nested:
  nested: 1
  var: '{{ $.Release.Name }}'

args:
  - --one
  - --two
  - --three
  - '{{ $.Release.Namespace }}'

keyVar:
  "{{ $.Release.Name }}": '{{ $.Release.Namespace }}'
  "multiline": >-
    {{ template "to-yaml.labels" $ }}
