apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: teleport-kube-agent
    repoURL: https://charts.releases.teleport.dev
    # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    targetRevision: 11.0.0
    helm:
      releaseName: teleport-kube-agent
      fileParameters:
        - name: authToken
          path: secrets+literal://ref+azurekeyvault://aks-credentials/teleport-node-token
      # language=yaml
      values: |
        kubeClusterName: jok
        proxyAddr: https://teleport.aks.jkroepke.de:443
        labels:
          env: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-teleport

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      managedFieldsManagers:
        - admissionsenforcer
