- name: Copy {{ certificate }} config
  copy:
    src: "files/{{ certificate }}-csr.json"
    dest: "{{ pki_dir }}/{{ certificate }}-csr.json"

- name: stat {{ certificate }}.pem
  stat:
    path: "{{ pki_dir }}/{{ certificate }}.pem"
  register: stat

- name: Generate {{ certificate }} certificate
  when: not stat.stat.exists
  shell: >-
    cfssl gencert
    -ca=ca.pem
    -ca-key=ca-key.pem
    -config=ca-config.json
    -profile=kubernetes
    {{ certificate }}-csr.json | cfssljson -bare {{ certificate }}
  args:
    chdir: "{{ pki_dir }}"
