- name: copy controller certificates
  copy:
    src: "{{ pki_dir }}/{{ item.1 }}"
    dest: "/root/{{ item.1 }}"
  delegate_to: "{{ item.0 }}"
  loop: "{{ data[0]|product(data[1])|list }}"
  vars:
    data:
      - "{{ groups.tag_controller_true }}"
      -
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem

- name: copy worker certificates
  copy:
    src: "{{ pki_dir }}/{{ item.1 }}"
    dest: "/root/{{ item.1 }}"
  delegate_to: "{{ item.0 }}"
  loop: "{{ data[0]|product(data[1])|list }}"
  vars:
    data:
      - "{{ groups.tag_controller_true }}"
      -
        - ca.pem

- name: copy worker certificate keys
  copy:
    src: "{{ pki_dir }}/{{ item }}-key.pem"
    dest: "/root/{{ item }}.pem"
  delegate_to: "{{ item }}"
  loop: "{{ groups.tag_worker_true }}"

- name: copy worker certificates
  copy:
    src: "{{ pki_dir }}/{{ item }}.pem"
    dest: "/root/{{ item }}.pem"
  delegate_to: "{{ item }}"
  loop: "{{ groups.tag_worker_true }}"
