- copy:
    content: KUBELET_EXTRA_ARGS=--cloud-provider=external
    dest: /etc/default/kubelet

- command: >-
    kubeadm init phase kubeconfig kubelet --config /etc/kubernetes/kubeadm/config.yaml

- command: >-
    kubeadm init phase kubelet-start --config /etc/kubernetes/kubeadm/config.yaml

- name: Start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
