# See: https://kubernetes.io/docs/setup/best-practices/certificates/

- name: set etcd certificates
  set_fact:
    kubernetes_certificates:
      - { name: apiserver, extended_key_usage: ["serverAuth"], subject: omit }
      - { name: apiserver-kubelet-client, extended_key_usage: ["clientAuth"], subject: "system:masters" }
      - { name: sa, extended_key_usage: ["clientAuth"], subject: omit }
      - { name: admin, extended_key_usage: ["clientAuth"] }
      - { name: kubelet, extended_key_usage: ["clientAuth"] }
      - { name: controller-manager, extended_key_usage: ["clientAuth"] }
      - { name: scheduler, extended_key_usage: ["clientAuth"] }
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:{{ ansible_hostname }}"
      - "DNS:localhost"
      - "IP:{{ ansible_default_ipv6.address }}"
      - "IP:{{ ansible_default_ipv4.address }}"
      - "IP:127.0.0.1"
      - "IP:::1"
      - "kubernetes"
      - "kubernetes.default"
      - "kubernetes.default.svc"
      - "kubernetes.default.svc.cluster"
      - "kubernetes.default.svc.cluster.local"

- name: create key for etcd certificates
  openssl_privatekey:
    path: /etc/etcd/{{ item.name }}.key
    size: 2048
    type: RSA
  loop: "{{ kubernetes_certificates }}"

- name: create csr for etcd certificates
  openssl_csr:
    path: /etc/etcd/{{ item.name }}.csr
    privatekey_path: /etc/etcd/{{ item.name }}.key
    common_name: "{{ ansible_fqdn }}"
    subject: "{{ item.subject }}"
    subject_alt_name: "{{ subject_alt_name if 'serverAuth' in item.extended_key_usage else omit }}"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage: "{{ item.extended_key_usage }}"
  loop: "{{ kubernetes_certificates }}"

- name: sign etcd certificates
  openssl_certificate:
    path: /etc/etcd/{{ item.name }}.crt
    csr_path: /etc/etcd/{{ item.name }}.csr
    ownca_path: /etc/etcd/ca.crt
    ownca_privatekey_path: /etc/etcd/ca.key
    ownca_not_after: "+3650d"
    provider: ownca
  loop: "{{ kubernetes_certificates }}"

