- name:  kubectl config set-cluster
  shell: >-
    kubectl config set-cluster kubernetes-the-hard-way
    --certificate-authority={{ pki_dir }}/ca.pem
    --embed-certs=true
    --server=https://{{ kubernetes_public_hostname }}:6443
    --kubeconfig={{ kubeconfig }}.kubeconfig
  args:
    chdir: "{{ kubeconfig_dir }}"

- name: kubectl config set-credentials
  shell: >-
    kubectl config set-credentials system:node:{{ kubeconfig }}
    --client-certificate={{ pki_dir }}/{{ kubeconfig }}.pem
    --client-key={{ pki_dir }}/{{ kubeconfig }}-key.pem
    --embed-certs=true
    --kubeconfig={{ kubeconfig }}.kubeconfig
  args:
    chdir: "{{ kubeconfig_dir }}"

- name: kubectl config set-context
  shell: >-
    kubectl config set-context default
    --cluster=kubernetes-the-hard-way
    --user=system:node:{{ kubeconfig }}
    --kubeconfig={{ kubeconfig }}.kubeconfig
  args:
    chdir: "{{ kubeconfig_dir }}"

- name: kubectl config use-context
  shell: >-
    kubectl config use-context default --kubeconfig={{ kubeconfig }}.kubeconfig
  args:
    chdir: "{{ kubeconfig_dir }}"
