# This password will become the domain admin password later when the system is promoted to a domain controller.
#- name: Set Password
#  win_user:
#    name: administrator
#    password: "{{ dc_password }}"
#    state: present
#  ignore_errors: True

#- name: Set upstream DNS server
#  win_dns_client:
#    adapter_names: '*'
#    ipv4_addresses:
#      - '{{ upstream_dns_1 }}'
#      - '{{ upstream_dns_2 }}'

- name: Install AD-Domain-Services
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature


- debug: var=win_feature
