# See: https://kubernetes.io/docs/setup/best-practices/certificates/

- name: set etcd certificates
  set_fact:
    etcd_certificates:
      - { name: healthcheck-client, extended_key_usage: ["clientAuth"], subject: omit }
      - { name: peer, extended_key_usage: ["clientAuth", "serverAuth"], subject: omit }
      - { name: server, extended_key_usage: ["clientAuth", "serverAuth"], subject: omit }
      - { name: apiserver-etcd-client, extended_key_usage: ["clientAuth"], subject: "system:masters" }
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "DNS:{{ ansible_hostname }}"
      - "DNS:localhost"
      - "IP:{{ ansible_default_ipv6.address }}"
      - "IP:{{ ansible_default_ipv4.address }}"
      - "IP:127.0.0.1"
      - "IP:::1"
- name: create key for etcd certificates
  openssl_privatekey:
    path: /etc/etcd/{{ item.name }}.key
    size: 2048
    type: RSA
  loop: "{{ etcd_certificates }}"

- name: create csr for etcd certificates
  openssl_csr:
    path: /etc/etcd/{{ item.name }}.csr
    privatekey_path: /etc/etcd/{{ item.name }}.key
    common_name: "{{ ansible_fqdn }}"
    subject: "{{ item.subject }}"
    subject_alt_name: "{{ subject_alt_name if 'serverAuth' in item.extended_key_usage else omit }}"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage: "{{ item.extended_key_usage }}"
  loop: "{{ etcd_certificates }}"

- name: sign etcd certificates
  openssl_certificate:
    path: /etc/etcd/{{ item.name }}.crt
    csr_path: /etc/etcd/{{ item.name }}.csr
    ownca_path: /etc/etcd/ca.crt
    ownca_privatekey_path: /etc/etcd/ca.key
    ownca_not_after: "+3650d"
    provider: ownca
  loop: "{{ etcd_certificates }}"

