packages:
  - containerd

write_files:
  - content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
    path: /etc/docker/daemon.json

runcmd:
  - [ cloud-init-per, once, sh, -c, "curl -sSfL https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.23.0/crictl-v1.23.0-linux-amd64.tar.gz | tar xf - -C /usr/local/bin/" ]


# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'
