# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "terraform-state"
    encrypt                     = true
    endpoint                    = "https://frw4trxpz16a.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
    force_path_style            = true
    key                         = "./mla.tfstate"
    region                      = "eu-frankfurt-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
  }
}
