- name: Install cri-o
  package:
    state: present
    name: cri-o,cri-o-runc,cri-tools

- name: Remove 100-crio-bridge.conf
  copy:
    content: ""
    dest: /etc/cni/net.d/100-crio-bridge.conf

- name: enable and start cri-o
  service:
    name: cri-o
    state: started
    enabled: yes


