version: '3.7'
services:
  nginx:
    image: openresty/openresty
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
