apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshell
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jkroepke/homelab.git
    targetRevision: HEAD
    path: aks/argocd/cloudshell/
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

