apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cortex
    repoURL: https://cortexproject.github.io/cortex-helm-chart
    targetRevision: 1.7.0
    helm:
      releaseName: cortex
      parameters:
        - name: image.tag
          value: master-250f7f3
      fileParameters:
        - name: "config.alertmanager.storage.azure.user_assigned_id"
          path: "kubectl://infra-cortex/sa/cortex/jsonpath={.metadata.annotations.azure\\\\.workload\\\\.identity/client-id}"
        - name: "config.ruler.storage.azure.user_assigned_id"
          path: "kubectl://infra-cortex/sa/cortex/jsonpath={.metadata.annotations.azure\\\\.workload\\\\.identity/client-id}"
        - name: "config.storage.azure.user_assigned_id"
          path: "kubectl://infra-cortex/sa/cortex/jsonpath={.metadata.annotations.azure\\\\.workload\\\\.identity/client-id}"
      #language=yaml
      values: |
        alertmanager:
          enabled: false
        distributor:
          enabled: true
          replicas: 1
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        ingester:
          enabled: true
          replicas: 1
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
          persistentVolume:
            enabled: false
        ruler:
          enabled: true
          replicas: 1
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        querier:
          enabled: true
          replicas: 1
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        
        query_frontend:
          enabled: true
          replicas: 1
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack

        table_manager:
          replicas: 1
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
        
        nginx:
          enabled: true
          replicas: 1
        
        store_gateway:
          enabled: true
          persistentVolume:
            enabled: false
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
        
        compactor:
          enabled: true
          replicas: 1
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
          persistentVolume:
            enabled: false
        
        config:
          auth_enabled: false
          ingester:
            lifecycler:
              ring:
                replication_factor: 1
          alertmanager:
            enable_api: true
              
          alertmanager_storage:
            azure:
              account_name: jokmspcortex
              container_name: alertmanager
              #user_assigned_id: '{{ get ((lookup "v1" "ServiceAccount" $.Release.Namespace "cortex").metadata.annotations) "azure.workload.identity/client-id" }}'
          ruler:
            enable_api: true
          ruler_storage:
            azure:
              account_name: jokmspcortex
              container_name: ruler
              #user_assigned_id: '{{ get ((lookup "v1" "ServiceAccount" "infra-cortex" "cortex").metadata.annotations) "azure.workload.identity/client-id" }}'
          
          storage:
            azure:
              account_name: jokmspcortex
              container_name: cortex
              #user_assigned_id: '{{ get ((lookup "v1" "ServiceAccount" $.Release.Namespace "cortex").metadata.annotations) "azure.workload.identity/client-id" }}'

        serviceAccount:
          create: false

        memcached:
          enabled: false
        memcached-index-read:
          enabled: false
        memcached-index-write:
          enabled: false
        memcached-frontend:
          enabled: false
        memcached-blocks-index:
          architecture: "standalone"
          replicaCount: 1
        memcached-blocks:
          architecture: "standalone"
          replicaCount: 1
        memcached-blocks-metadata:
          architecture: "standalone"
          replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-cortex

