apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.0
    helm:
      releaseName: crossplane
      values: |
        resourcesCrossplane:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
        
        resourcesRBACManager:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
        provider:
          packages:
            - xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.0


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-crossplane
---
apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: infra-crossplane
      name: azure-account-creds
      key: credentials
