apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.1
    helm:
      releaseName: crossplane
      values: |
        resourcesCrossplane:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0
        
        resourcesRBACManager:
          limits:
            cpu: 0
            memory: 0
          requests:
            cpu: 0
            memory: 0


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-crossplane
