apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dexidp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    # https://artifacthub.io/packages/helm/dex/dex
    targetRevision: 0.12.0
    helm:
      releaseName: dex
      fileParameters:
        - name: env.GITHUB_CLIENT_ID
          path: secrets+literal://ref+azurekeyvault://aks-credentials/dexidp-github-client-id
        - name: env.GITHUB_CLIENT_SECRET
          path: secrets+literal://ref+azurekeyvault://aks-credentials/dexidp-github-secret
        - name: env.ARGOCD_CLIENT_SECRET
          path: secrets+literal://ref+azurekeyvault://aks-credentials/dexidp-argocd-secret
        - name: env.GRAFANA_CLIENT_SECRET
          path: secrets+literal://ref+azurekeyvault://aks-credentials/dexidp-grafana-client-secret
      # language=yaml
      values: |
        config:
          issuer: https://login.aks.jkroepke.de/dex
          enablePasswordDB: false
          storage:
            type: memory
          
          oauth2:
            skipApprovalScreen: true
        
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: $GITHUB_CLIENT_ID
                clientSecret: $GITHUB_CLIENT_SECRET
                redirectURI: https://login.aks.jkroepke.de/dex/callback
                orgs:
                  - name: creativesandbox

          staticClients:
            - id: argocd
              redirectURIs:
                - 'https://argocd.aks.jkroepke.de/auth/callback'
              name: 'ArgoCD'
              secretEnv: ARGOCD_CLIENT_SECRET
            - id: grafana
              redirectURIs:
                - 'https://grafana.aks.jkroepke.de/login/generic_oauth'
              name: 'ArgoCD'
              secretEnv: GRAFANA_CLIENT_SECRET
        
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
          - host: login.aks.jkroepke.de
            paths:
              - path: /
                pathType: Prefix
          tls:
            - secretName: ingress-tls
              hosts:
                - login.aks.jkroepke.de
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-dexidp
