apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
    targetRevision: 41.5.1
    helm:
      releaseName: kube-prometheus-stack
      skipCrds: true
      fileParameters:
        - name: grafana.grafana\.ini.auth\.generic_oauth.client_secret
          path: secrets+literal://ref+azurekeyvault://aks-credentials/dexidp-grafana-client-secret
        - name: grafana.grafana\.ini.azure.managed_identity_client_id
          path: "kubectl://infra-prometheus/sa/grafana/jsonpath={.metadata.annotations.azure\\\\.workload\\\\.identity/client-id}"
      # language=yaml
      values: |
        defaultRules:
          create: true
          rules:
            etcd: false
            kubeControllerManager: false
            kubeProxy : false
            kubeSchedulerAlerting: false
            kubeSchedulerRecording: false
          disabled:
            PrometheusNotConnectedToAlertmanagers: true
    
        alertmanager:
          enabled: false
        prometheus:
          prometheusSpec:
            scrapeInterval: 30s
            remoteWrite:
            - url: http://cortex-nginx.infra-cortex.svc/api/v1/push
            remoteWriteDashboards: true
            
            enableFeatures:
              - new-service-discovery-manager
            #   - agent
            # # https://github.com/prometheus-community/helm-charts/issues/2506#issuecomment-1277362029
            # containers:
            # - name: prometheus
            #   args:
            #     - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
            #     - '--storage.agent.path=/prometheus'
            #     - '--enable-feature=new-service-discovery-manager,agent'
            #     - '--web.enable-lifecycle'
            #     - '--web.console.templates=/etc/prometheus/consoles'
            #     - '--web.console.libraries=/etc/prometheus/console_libraries'
            #     - '--web.external-url=http://kube-prometheus-stack-prometheus.infra-prometheus:9090'
            #     - '--web.route-prefix=/'
            #     - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'
          
          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
              nginx.ingress.kubernetes.io/auth-url: "https://login.aks.jkroepke.de/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://login.aks.jkroepke.de/oauth2/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri"
              cert-manager.io/cluster-issuer: letsencrypt
            ingressClassName: nginx
            paths:
              - /
            hosts:
              - prometheus.aks.jkroepke.de
            pathType: Prefix
            tls:
              - secretName: prometheus-ingress-tls
                hosts:
                  - prometheus.aks.jkroepke.de
   
        prometheusOperator:
          prometheusConfigReloader:
            resources:
              requests:
                cpu: 0
                memory: 0
              limits:
                cpu: 0
                memory: 0
          admissionWebhooks:
            patch:
              enabled: false
            certManager:
              enabled: true
        
        grafana:
          serviceAccount:
            create: false
            name: grafana
          testFramework:
            enabled: false
          env:
            GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - grafana.aks.jkroepke.de
            tls:
              - secretName: grafana-ingress-tls
                hosts:
                  - grafana.aks.jkroepke.de
          grafana.ini:
            server:
              root_url: https://grafana.aks.jkroepke.de
            auth:
              oauth_auto_login: true
            azure:
              managed_identity_enabled: true
            users:
              auto_assign_org_role: Admin
              disable_login_form: true
            auth.generic_oauth:
              enabled: true
              allow_sign_up: true
              name: login.aks.jkroepke.de
              client_id: grafana
              scopes: openid profile email
              auth_url: https://login.aks.jkroepke.de/dex/auth
              token_url: https://login.aks.jkroepke.de/dex/token
              api_url: https://login.aks.jkroepke.de/dex/userinfo
              use_pkce: true
        
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: 'grafana-net'
                type: file
                disableDeletion: true
                editable: false
                options:
                  path: /var/lib/grafana/dashboards/default
          dashboards:
            default:
              cert-manager:
                gnetId: 11001
                revision: 1
                datasource: Cortex
              nginx-ingress-exporter:
                gnetId: 9614
                revision: 1
                datasource: Cortex
              node-exporter-full:
                gnetId: 1860
                revision: 27
                datasource: Cortex
              kube-state-metrics-v2:
                gnetId: 13332
                revision: 12
                datasource: Cortex
              prometheus-2.0-overview:
                gnetId: 3662
                revision: 2
                datasource: Cortex
              argocd:
                gnetId: 14584
                revision: 1
                datasource: Cortex
                
          sidecar:
            datasources:
              defaultDatasourceEnabled: false
          additionalDataSources:
            - name: Cortex
              type: prometheus
              uid: cortex
              url: http://cortex-nginx.infra-cortex.svc/prometheus
              access: proxy
              isDefault: true
              jsonData:
                timeInterval: 1m
            - name: Loki
              type: loki
              uid: loki
              url: http://loki-gateway.infra-loki.svc/
              access: proxy
              isDefault: false
            - name: "Azure Monitor"
              type: grafana-azure-monitor-datasource
              uid: azure-monitor-datasource
              orgId: 1
              access: proxy
              isDefault: false
              readOnly: true
              jsonData:
                cloudName: azuremonitor
                azureAuthType: msi
              version: 5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-prometheus
---
# ref: https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-41.5.1
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-prometheus
