apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.2.2
    helm:
      releaseName: loki
      fileParameters:
        - name: "loki.storage_config.azure.user_assigned_id"
          path: "kubectl://infra-loki/sa/loki/jsonpath={.metadata.annotations.azure\\\\.workload\\\\.identity/client-id}"
      #language=yaml
      values: |
        loki:
          podAnnotations:
            azure.workload.identity/inject-proxy-sidecar: "true"
            
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: "azure"
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
          serviceAccount:
            create: false
            name: loki
          storage_config:
            azure:
              account_name: jokmspaks
              container_name: loki
              use_managed_identity: true
            boltdb_shipper:
              active_index_directory: /data/loki/boltdb-shipper-active
              cache_location: /data/loki/boltdb-shipper-cache
              cache_ttl: 24h
              shared_store: azure
            filesystem:
              directory: /data/loki/chunk
          schemaConfig:
            configs:
            - from: 2022-01-11
              store: boltdb-shipper
              object_store: azure
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
            
        monitoring:
          alerts:
            labels:
              release: kube-prometheus-stack
          rules:
            labels:
              release: kube-prometheus-stack
          serviceMonitor:
            labels:
              release: kube-prometheus-stack
          
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
            

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-loki

