apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    targetRevision: 4.3.0
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: controller.service.annotations.service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path
          value: /healthz
        - name: controller.metrics.serviceMonitor.enabled
          value: "true"
        - name: controller.metrics.serviceMonitor.additionalLabels.release
          value: "kube-prometheus-stack"
      values: |
        controller:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 0
              memory: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra-ingress-nginx

