apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: renovate-oci-demo/chart/renovate-oci-demo
    repoURL: gcr.io:443
    targetRevision: 2.0.0
    helm:
      releaseName: renovate-oci-demo
      parameters:
        - name: image.tag
          value: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: oci-test
