---
nameOverride: cluster-autoscaler
cloudProvider: aws
awsRegion: eu-central-1
autoDiscovery:
  clusterName: joe-k8s-sandbox
nodeSelector:
  node-role.kubernetes.io/master: ""
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
extraArgs:
  balance-similar-node-groups: true
  cluster-name: joe-k8s-sandbox
  scale-down-enabled: true
  scale-down-delay-after-add: 10m
  scale-down-delay-after-delete: 0s
  scale-down-delay-after-failure: 3m
  scale-down-unneeded-time: 10m
  skip-nodes-with-system-pods: false
