# Oauth client configuration specifics
config:
  clientID: "kubernetes"
  clientSecret: "kubernetes"
  cookieSecret: "bTE3dDNMaTV3RFNoS1VkaDBvMEl3SzJBR1FhcitlVzA="
  configFile: null
  google: {}

image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "v5.1.0"
  pullPolicy: "IfNotPresent"

extraArgs:
  provider: oidc
  provider-display-name: Keycloak
  oidc-issuer-url: "https://login.joe-k8s-sandbox.adorsys-sandbox.aws.adorsys.de/auth/realms/kubernetes"
  keycloak-group: k8s-admin
#  scope: "openid email profile groups offline_access"
  scope: "openid email"

  email-domain: '*'
  pass-authorization-header: 'true'
  ssl-upstream-insecure-skip-verify: 'true'
  reverse-proxy: 'true'

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: "nginx"

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

# Whether to use secrets instead of environment values for setting up OAUTH2_PROXY variables
proxyVarsAsSecrets: true

securityContext:
  enabled: true
  runAsNonRoot: true

httpScheme: http
