/*
  Important Security Notice

  The private key generated by this resource will be stored unencrypted in your Terraform state file.

  ** Use of this resource for production deployments is not recommended. **

  Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.
*/

resource "tls_private_key" "kubernetes-ca" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "kubernetes-ca" {
  key_algorithm   = tls_private_key.kubernetes-ca.algorithm
  private_key_pem = tls_private_key.kubernetes-ca.private_key_pem

  subject {
    common_name  = "kubernetes CA"
    organization = var.name
  }

  validity_period_hours = local.validity_period_hours

  is_ca_certificate = true

  allowed_uses = [
    "cert_signing",
    "crl_signing"
  ]
}
