#cloud-config

runcmd:
  - cloud-init-per once -- kubeadm join --node-name "$(hostname -f)" --config /etc/kubernetes/kubeadm.yaml

# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'
