bootcmd:
  - |
    while [ `lsblk | grep disk | wc -l` -lt ${count} ]; do
        echo [`date --rfc-3339=ns`] waiting on disks ... expected ${count} found `lsblk | grep disk | wc -l`;
        sleep 5;
    done

disk_setup:
  /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_${ebs.etcd}:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: etcd
    filesystem: ext4
    device: /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_${ebs.etcd}
    partition: auto
    overwrite: false

growpart:
  mode: auto
  devices:
    - "/"
    - "/var/lib/etcd"

mount_default_fields: [none, none, "auto", "defaults,nofail,x-systemd.automount,x-systemd.requires=cloud-init.service", "0", "2"]
mounts:
  - [ /dev/disk/by-label/etcd, /var/lib/etcd ]
