#cloud-config

timezone: Europe/Berlin
locale: C.UTF-8

package_update: true
package_upgrade: true
apt_reboot_if_required: true

packages:
  - git
  - ansible

runcmd:
  - >-
    cloud-init-per once
    --
    ansible-pull
    --accept-host-key
    --purge
    --url https://github.com/jkroepke/kubernetes-the-hard-way.git
    --checkout ansible
    --directory /tmp/ansible/
    --tags common,cri-o,etcd,controller
    challenge/ansible/local.yml

apt:
  ansible:
    source: 'ppa:ansible/ansible'
