timezone: Europe/Berlin
locale: C.UTF-8

package_update: true
package_upgrade: true
apt_reboot_if_required: true

packages:
  - git
  - ansible

runcmd:
  - >-
    cloud-init-per once
    --
    ansible-pull
    --accept-host-key
    --purge
    --url https://github.com/jkroepke/kubernetes-the-hard-way.git
    --checkout ansible
    --directory /tmp/ansible/
    --tags common,cri-o,etcd,kubernetes,controller
    --extra-vars /etc/ansible/vars.yml
    challenge/ansible/local.yml

# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'
