#cloud-config

timezone: Europe/Berlin
locale: C.UTF-8

package_update: true
package_upgrade: true
apt_reboot_if_required: true

packages:
  - git
  - ansible

growpart:
  mode: auto
  devices:
    - "/"
    - "/var/lib/etcd"

runcmd:
  - cloud-init-per once ansible-pull

apt:
  ansible:
    source: 'ppa:ansible/ansible'
