#cloud-config

apt:
  sources:
    libcontainers.list:
      source: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
      keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4

    cri-o.list:
      source: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${versions.cri-o}/xUbuntu_20.04/ /
      keyid: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4

packages:
  - cri-o
  - cri-o-runc
  - cri-tools

# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'
