#cloud-config

bootcmd:
  - |
    while [ `lsblk | grep disk | wc -l` -lt ${total_disk_count} ]; do
        echo [`date --rfc-3339=ns`] waiting on disks ... expected ${total_disk_count} found `lsblk | grep disk | wc -l`;
        sleep 5;
    done

disk_setup:
  /dev/nvme1n1:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: etcd
    filesystem: ext4
    device: /dev/nvme1n1
    partition: auto
    overwrite: false

growpart:
  mode: auto
  devices:
    - "/"
    - "/dev/disk/by-label/etcd"
  ignore_growroot_disabled: true

mount_default_fields: [none, none, "auto", "defaults,nofail,x-systemd.automount,x-systemd.requires=cloud-init.service", "0", "2"]
mounts:
  - [ /dev/disk/by-label/etcd, /var/lib/etcd ]

# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'
