---
helmDefaults:
  wait: true
  timeout: 1800
  atomic: true
  cleanupOnFail: true
  skipDeps: false

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "3.11.0"
    values:
      - ../values/ingress-nginx.yaml
