---
helmDefaults:
  wait: true
  timeout: 1800
  atomic: true
  cleanupOnFail: true
  skipDeps: false

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "v1.0.1"
    values:
      - ../values/cert-manager.yaml

  - name: cert-manager-cluster-issuer
    needs: ['cert-manager/cert-manager']
    namespace: cert-manager
    chart: ../cert-manager-cluster-issuer
    disableValidation: true
