---
helmDefaults:
  wait: true
  timeout: 1800
  atomic: true
  cleanupOnFail: true
  skipDeps: false

repositories:
  - name: uswitch
    url: https://uswitch.github.io/kiam-helm-charts/charts/

releases:
  - name: kiam
    namespace: kiam
    disableValidation: true
    chart: uswitch/kiam
    version: 5.9.0
    values:
      - ../values/kiam.yaml
