scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep

      - source_labels: [ __address__, __meta_docker_container_label_prometheus_port ]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [ __meta_docker_container_label_prometheus_path ]
        action: replace
        regex: (.+)
        target_label: __metrics_path__

      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
