name: Update Chart.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify Chart.yaml
        run: |
          echo "${{ github.sha }}" > commit.txt

      - name: Commit Changes Using GraphQL API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |      
          curl https://api.github.com/graphql -f \
               --write-out '%{stderr}HTTP status: %{response_code}\n\n'
               -H "Authorization: bearer $GITHUB_TOKEN" \
               --data @- <<GRAPHQL | jq
          {
            "query": "mutation (\$input: CreateCommitOnBranchInput!) {
              createCommitOnBranch(input: \$input) { 
                commit { 
                  url 
                } 
              } 
            }",
            "variables": {
              "input": {
                "branch": {
                  "repositoryNameWithOwner": "${{ github.repository }}",
                  "branchName": "${{ github.ref_name }}"
                },
                "message": { "headline": "Update Chart.yaml" },
                "fileChanges": {
                  "additions": [
                    {
                      "path": "commit.txt",
                      "contents": "$(cat commit.txt | base64 -w 0)"
                    }
                  ]
                },
                "expectedHeadOid": "${{ github.sha }}"
              }
            }
          }
          GRAPHQL
