name: "helmfile"
on:
  workflow_dispatch:
jobs:
  plan:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
        with:
          version: 3.12.0
      - uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-version: 'v0.153.1'
          helm-version: 'v3.11.1'
          helm-plugins: https://github.com/databus23/helm-diff
          helmfile-args: version
      - uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-version: 'v0.153.1'
          helm-version: 'v3.12.0'
          helm-plugins: https://github.com/databus23/helm-diff
          helmfile-args: version
