name: Update Chart.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:


0a5d4f0d7424134386d2e2c8a325493ad73ec4be
